### ISSUE TITLE
New swipl tarbar names breaks install

### ISSUE THREAD

**Issue by jamesnvc** [fnogatz/swivm#15]
It seems that untar'ing the recent tarballs ends up with a directory named `swipl-devel-$VERSION`, instead of the `swipl-$VERSION` that swivm expects.

It also seems that the tarbars are now missing the git submodules; not sure if this is an issue on SWI's end, or something that swivm can do.

I've experienced this with the swivm 0.5 on both macOS & Ubuntu Linux trying to install both 8.1.9 and 8.1.6.

**Comment by fnogatz** [comment]
Hi James, thank you for reporting this. Note that the latest version of swivm is 0.5.1, though the most recent changes should have no effect on the issue reported here.

I tried the installation of `8.1.6` and `8.1.9` (`swivm install 8.1.9`) and everything works as expected. Also the tarballs provided by SWI-Prolog look correct. Could you please provide the error message(s) you experienced?

**Comment by jamesnvc** [comment]
Strange; updated to 0.5.1 & seeing the same issue.

Error looks like this on linux machine (same error on macOS for me):

```
james@gonk:~$ swivm install 8.1.7
Downloading https://github.com/SWI-Prolog/swipl-devel/archive/V8.1.7.tar.gz...
mv: cannot stat '/home/james/.swivm/src/swipl-8.1.7': No such file or directory
mv: cannot stat '/home/james/.swivm/src/pl-8.1.7': No such file or directory
swivm: install 8.1.7 failed!
```

And then I can look inside the .swivm/src directory and see `swipl-8.1.7.tar.gz` and the directory `swipl-devel-8.1.7`

**Comment by fnogatz** [comment]
Okay, normally downloading from `https://github.com/SWI-Prolog/swipl-devel/archive/...` is only the second option. The default is to use `http://www.swi-prolog.org/download` instead. Which is no longer active, since SWI-Prolog moved to https [4 weeks ago](https://swi-prolog.discourse.group/t/www-swi-prolog-org-goes-https/811) :laughing: 

I changed the default download path to https accordingly, so `echo $SWIVM_MIRROR` should return `https://www.swi-prolog.org/download` as of swivm of version `0.5.2`, which I just released.

Please try it with the new version. Then, I could open another issue to fix the handling of the `github.com` download source.

**Comment by jamesnvc** [comment]
Hm, still isn't working; seems to be because the check on line 773 now fails, because the fancy new HTTPS server is using the brusque HTTP/2 status; curling looks like

```
HTTP/2 200
server: nginx/1.14.0 (Ubuntu)
content-type: application/x-gzip
last-modified: Mon, 03 Jun 2019 20:39:24 GMT
via: 1.1 varnish
accept-ranges: bytes
age: 276
accept-ranges: bytes
date: Wed, 10 Jul 2019 21:53:13 GMT
via: 1.1 varnish
x-served-by: cache-sea1028-SEA, cache-yyz8327-YYZ
x-cache: MISS, HIT
x-cache-hits: 0, 0
x-timer: S1562795593.264418,VS0,VE5
strict-transport-security: max-age=900
content-length: 10650684
```

but swivm is checking for '200 OK', which it doesn't see, so it still falls back to github.

**Comment by fnogatz** [comment]
> but swivm is checking for '200 OK', which it doesn't see, so it still falls back to github.

Good catch. I fixed this in version `0.5.3`.

**Comment by jamesnvc** [comment]
Awesome, looks good to me now! Can we close this issue & let #16 handle the tarball name issue then?

**Comment by fnogatz** [comment]
Alright, this issue seems to be fixed now. Everything regarding the downloads from GitHub are handled in #16, so I close this issue here. Thank you for your help!
